insert into authors (id, author) values (1, 'Sheelah Collier');
insert into authors (id, author) values (2, 'Vergil Moquin');
insert into authors (id, author) values (3, 'Lolly Kemson');
insert into authors (id, author) values (4, 'Walther Ellissen');
insert into authors (id, author) values (5, 'Maurise Kernocke');
insert into authors (id, author) values (6, 'Phyllys Duncklee');
insert into authors (id, author) values (7, 'Marge Fitzmaurice');
insert into authors (id, author) values (8, 'Launce Thaller');
insert into authors (id, author) values (9, 'Preston Darnborough');
insert into authors (id, author) values (10, 'Carlyle Francke');
insert into authors (id, author) values (11, 'Isador Lachaize');
insert into authors (id, author) values (12, 'Terry Hooke');
insert into authors (id, author) values (13, 'Rochelle Lembcke');
insert into authors (id, author) values (14, 'Edita McKleod');
insert into authors (id, author) values (15, 'Mozelle Gilfether');
insert into authors (id, author) values (16, 'Dimitri Pandie');
insert into authors (id, author) values (17, 'Berny Legen');
insert into authors (id, author) values (18, 'Gerry Cariss');
insert into authors (id, author) values (19, 'Phillip Ashmore');
insert into authors (id, author) values (20, 'Madeline Riggoll');
insert into authors (id, author) values (21, 'Clementius Brundrett');
-- insert into authors (id, first_name, last_name) values (1, 'Carlos', 'Dodshon');
-- insert into authors (id, first_name, last_name) values (2, 'Jelene', 'Hopfner');
-- insert into authors (id, first_name, last_name) values (3, 'Dannye', 'Wickendon');
-- insert into authors (id, first_name, last_name) values (4, 'Alec', 'Shurrock');
-- insert into authors (id, first_name, last_name) values (5, 'Nadia', 'Brabham');
-- insert into authors (id, first_name, last_name) values (6, 'Silvie', 'Gateland');
-- insert into authors (id, first_name, last_name) values (7, 'Sharai', 'Feighney');
-- insert into authors (id, first_name, last_name) values (8, 'Andres', 'Djorevic');
-- insert into authors (id, first_name, last_name) values (9, 'Deeanne', 'Rivitt');
-- insert into authors (id, first_name, last_name) values (10, 'Javier', 'MacCallister');
-- insert into authors (id, first_name, last_name) values (11, 'Ami', 'Ramsbotham');
-- insert into authors (id, first_name, last_name) values (12, 'Georges', 'Smiley');
-- insert into authors (id, first_name, last_name) values (13, 'Nichol', 'Brick');
-- insert into authors (id, first_name, last_name) values (14, 'Dorris', 'Eastup');
-- insert into authors (id, first_name, last_name) values (15, 'Ewen', 'Chrestien');
-- insert into authors (id, first_name, last_name) values (16, 'Allin', 'Gilluley');
-- insert into authors (id, first_name, last_name) values (17, 'Verney', 'Lambdon');
-- insert into authors (id, first_name, last_name) values (18, 'Margalit', 'Mitten');
-- insert into authors (id, first_name, last_name) values (19, 'Rhonda', 'Peterson');
-- insert into authors (id, first_name, last_name) values (20, 'Melinde', 'Badsey');
-- insert into authors (id, first_name, last_name) values (21, 'Alexander', 'Cherrington');


insert into books (id, price, price_old, title, author_id) values (1, 605, 1476, 'Andalax', 13);
insert into books (id, price, price_old, title, author_id) values (2, 999, 1237, 'Voyatouch', 18);
insert into books (id, price, price_old, title, author_id) values (3, 1081, 1369, 'Voyatouch', 5);
insert into books (id, price, price_old, title, author_id) values (4, 926, 958, 'Tin', 19);
insert into books (id, price, price_old, title, author_id) values (5, 1188, 887, 'Mat Lam Tam', 17);
insert into books (id, price, price_old, title, author_id) values (6, 987, 1418, 'Fintone', 8);
insert into books (id, price, price_old, title, author_id) values (7, 1116, 1484, 'Lotstring', 15);
insert into books (id, price, price_old, title, author_id) values (8, 716, 671, 'Mat Lam Lam', 14);
insert into books (id, price, price_old, title, author_id) values (9, 1141, 1457, 'Tin', 11);
insert into books (id, price, price_old, title, author_id) values (10, 869, 1310, 'Asoka', 16);
insert into books (id, price, price_old, title, author_id) values (11, 1092, 735, 'Alpha', 1);
insert into books (id, price, price_old, title, author_id) values (12, 530, 1432, 'Hatity', 20);
insert into books (id, price, price_old, title, author_id) values (13, 1046, 600, 'Konklab', 12);
insert into books (id, price, price_old, title, author_id) values (14, 886, 1116, 'Zaam-Dox', 1);
insert into books (id, price, price_old, title, author_id) values (15, 677, 1476, 'Flowdesk', 16);
insert into books (id, price, price_old, title, author_id) values (16, 810, 892, 'Zontrax', 2);
insert into books (id, price, price_old, title, author_id) values (17, 860, 1270, 'Ventosanzap', 13);
insert into books (id, price, price_old, title, author_id) values (18, 927, 1445, 'Home Ing', 1);
insert into books (id, price, price_old, title, author_id) values (19, 1190, 647, 'Namfix', 1);
insert into books (id, price, price_old, title, author_id) values (20, 522, 1101, 'Kanlam', 15);
insert into books (id, price, price_old, title, author_id) values (21, 647, 1054, 'Cardguard', 16);
